version = "0.0.0"
copyright = "Copyright (c) 2025â€“2026 The Rocket Authors"

[flags]

[sourcemap]
filename = "sourcemap.json"
project = "default.project.json"

[build]
src = "src"
extensions = "extensions"

output = "out"
model = "Rocket.rbxm"
project = "build.project.json"
